os: osx
osx_image: xcode11.6
language: swift
script: xcodebuild clean build test -workspace Spendee.xcworkspace -scheme "Spendee" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.6,name=iPhone 8" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
